version: '3'

services:
  app:
    build:
      context: node
      dockerfile: Dockerfile.dev
    container_name: app
    ports:
      - 80:3000
    volumes:
      - ./node:/usr/src/app
    entrypoint: npm run dev
    networks:
      - std-network

networks:
  std-network:
    driver: bridge